name: Django Tests

on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main

# on:
#   schedule:
#     - cron:  '*/15 * * * *'

jobs:
  build:

    runs-on: python:3.8-slim

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --no-cache-dir -q 'pipenv==2018.11.26'
        pipenv install --deploy --system
    - name: Lint with flake8
      run: |
        pipenv install flake8
        pipenv install pytest
        flake8
    - name: Coverage report
      run: |
        pip install coverage
        coverage run manage.py test
        coverage report
    - name: Django Testing
      run: |
        python3 manage.py test

    - name: pytest
        run: |
          pytest tests
